branches:
  only:
  - master
language: python
python:
- '3.5'
services:
- docker
sudo: required
env:
  global:
  - VERSION=r2019a_p37
  - DOCKER_REPO=spectreteam/python_mcr
  - secure: MjBpNDtoOHA7KK+6WwsianAwEIfNRGJsJ/G6lEfI20u9zDd7B7cr+PsR2x5McM37WfIeW/IJFMYV91GcAT5+mlEZ85/ljzdb48X4wVQh9VP3ieIzxyt/QLWLQNpPpc2UlcROn6GTswgYomj00EHsnyMofTLtf9vuTEguUXbMVbLhn07Jb+uOyQuwg1M1oDSaeK7JIUA1xrKhQRoL1GoNXRpV/aKr2iscXOKJpyJmIQem+Lhhhf+tJhV6BSy03J8UaG+0LS5/Ao4hdUV7QfFngJi6xcamiHxT7/P1aZe6GzyueMf1iM+roTPld9tv3iORrdZCEdUSJl/4IYBbHf5HdgnPGmdtic9TPh81KsWNk1TG/or30ADntr3h8kTLX1duMUoHVvnCL7eX858NC3e8h12/+XkmWIEv6v9ETwXXCIPy/mdpiLGFQV3O07xJIFIdS9b2Kk36Fp59BtF6NBxEOrKSuUkDM7kCXmHTXDFH7C3qFO4EG9dhxNGXuOKgI2SRe5+o6CTOL92rapNPgVQzvjYHdWqoPtyrEGj4mwDA/pc4JGLGFPG58ttC0qX4LRCinNNSQRNTy85mvZL3APUNoCd+D09zLdoBomZ4GEwJcrQw6r1qlcLOLZj5COEuUobn4CJCCNfRYtO8WmkRLscviIxlbdUDhoOqXvj708j57zI=
  - secure: AHCYetkj1E9+ETaETSBf2kIwPjetDwYoAYJ8JlXoGyBuQPlsAaUtRY6JCLFKxCJTOuIPoznpCP38O8ye30bfncK0jWOklGMQlf+4t7N3oy2N5POZU3NRL6vRddkRhRD2jy8mJKUuMZlUWgI8LZ005P81TS/KoEUqHf7OoMVnhmKwkHqUAbKE9FMQ7l2l0qS8hxlSGE/tCAYLAclGJMIV9hUA14OcoWrCcZtiquOwVtx3A3A6bp1j5zSJeLlySVv87cdwh5yz73PSzY5DpyuqT7SQmc2JD6Z0noKaS8ByaB5ncuOW/b86t0V4okL8o7EItpxv4mX13kZrlYubdMmBlkn6xDDz6hE4Mh3sBKBCJ/in/S5N5AVx1658pjShO7rPfgKLTMmB7Jy4Bf7UgtUn2bFiKoQWpYsWCzSgOQaUHmR63CbkVz1Bno1xJWpf3GRnQ+iC6O5dAdpA7fgYb5Wnu1h4uiX7ut3V5AFT/a4Grb2TpqHGVuRudDHQUa9WladO5T3Y3XWHYj1uQMduUWEURUP9E9dmYPd78zr/WbhGNk7b1jAKr82wP8VIt3myedwvtftUXfnSGKDVe2wu/5oV+bw7DyY/rNuSLZsLovD8+WyJQdmcOvuZvbg5wnCJyhYpJvxQOhvhGJrIUujBIM4y0ENNBqQXbK9q8NmmRJZLgS4=
install:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
script:
- docker build -t $DOCKER_REPO:$VERSION .
- docker push $DOCKER_REPO:$VERSION
notifications:
  webhooks:
    urls:
      secure: WG6PWtstzqE07MMIlZA8HsSIMP1tdMWCZG1y1Rk5yori4rztPFtobjRHfd2lNcE5d3Vv3PSVHZ3zY8948zb8t17/hUhX2E6SOSAzXamEDBC3inGxK1cVsJ5wzRBfxpQLLeVg82VCXSfsBGSi5qNumXFAi8lf8coKP2fVzzcSqI2LSDiMDVmPxv+LhURt8XhhAxiXiOJS12tpPv6NFxrt7y8RdOqGox/gt+JwaGPJK+hTsF/jOZpbjf9hbkQTktZ3V2px8ouRIfdX2x7wYjhrbU2wxHFYrM+JwtepOYmNbfc3VoquPNu5z6EnQOwClI6myLBy/rh/03yhDiyJtECZg3I07qapb+t5If8CM5I768rPKvCMrnNPMHd5lp+PVvXu7JwPxoEVlSWNY84PmWUUZ6WFG4zGKBNg9lqyO14DYf072/yke/Lp4DH2xRqgAcssIFnf4j/+TPwzTwivlpSOIaXbv+5ofH2aaMU9Y9d/Z6JwJrJ7vnlht5mzQqboJYlhq5QuVimssdp1dxy+HkIvQ2gnJfugEUuXRGC4HY/PgUF3oBqI1pQuj+xmVGF0ZYm+oB5mwdEWtLWBTGFn1YNWgHlmvzebgpcegMx7ZQKmKaT4jBlD2rAVKTPHe8H0rWY8GdjBrCD2tamnh/5K0Qtc9ZDF6yerEZUENxkD05P4zT0=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
